version: 2
jobs:
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
        - name: Install dependencies
        - command: npm install
      - run: 
        - name: Run unit tests
        - command: npm test
      - run: 
        - name: Generate code coverage
        - command: cat ./coverage/**/lcov.info | ./node_modules/codecov/bin/codecov
      - store_artefacts:
        - path: coverage
        - prefix: coverage
  deploy-master:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
        - name: Deploy to Master
        - command: git push git@heroku.com:taskmastr-staging.git master
  deploy-production:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
        - name: Deploy to Production
        - command: git push git@heroku.com:taskmastr-production.git master
      - run:
          name: Bust Cloudflare caches
          command: 
            - > 
              curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CLOUDFLARE_ZONE}/purge_cache"
              -H "X-Auth-Email: ${CLOUDFLARE_EMAIL}"
              -H "X-Auth-Key: ${CLOUDFLARE_AUTH}"
              -H "Content-Type: application/json"
              --data '{"files":["https://taskmastr.org/javascripts/bundle.js","https://taskmastr.org/stylesheets/styles.css"]}'
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - deploy-master:
        requires:
          - test
        filters:
          branches:
            only: master
      - deploy-production:
        requires:
          - test
        filters:
          branches:
            only: production
