export default {
  wiki: '//patrickfatrick.gitbooks.io/taskmastr/content/',
  repo: '//github.com/patrickfatrick/taskmastr',
  testUser: 'do-not-reply@taskmastr.org',
  testKey: 'S41iVAtINGREsIdUE-278',
  disconnect: false,
  deleteQueue: {},
  initialized: false,
  authenticated: false,
  forgot: false,
  create: false,
  currentList: '',
  reset: false,
  rememberMe: false,
  invalidKey: false,
  loginAttempt: false,
  createFail: '',
  forgotAttempt: false,
  forgotEmail: false,
  forgotFail: '',
  confirmAttempt: false,
  resetToken: null,
  resetAttempt: false,
  resetFail: '',
  jumpto: ''
}
