const year = new Date().getFullYear().toString()

export default {
  list: [
    'Remind me to eat lunch tomorrow',
    '/r Punch Bowl next Monday',
    '/y think of a New Year\'s Resolution',
    '/m pay rent',
    'Pay that bill',
    '/t stop playing WoW, maybe',
    '/t stop playing GTA, maybe',
    '/t stop playing Fallout, maybe',
    '/t stop playing Borderlands, maybe',
    '/t stop playing Pokemon, maybe',
    '/w Set up a meeting with the bigwigs',
    'Clean up all the poop in the back yard',
    'Start watching Mr. Robot',
    'Read Kavalier & Clay',
    'Walk the dog',
    'Remind me to water the plants on Tuesday',
    '/r get a costume on 10/30/' + year,
    '/r buy x-mas gifts Dec 24, ' + year,
    '/r learn how to juggle next year',
    '/r fix the chair on Sunday',
    '/r Check out the art walk next Friday',
    '/t meet Katie for lunch',
    'Buy a new bike',
    'Remind me to mow the lawn on Saturday',
    'Find the remote',
    'Finish Infinite Jest',
    '/t buy groceries',
    'Remind me to vacuum on Saturday',
    '/m Read the CliffsNotes for book club',
    '/y start saving for a house',
    '/r move into a new place next year',
    'Buy milk',
    'Buy dog food',
    'Take a shower',
    'Replace the ceiling fan',
    'Clean the sliding doors',
    'Implement that shiny new JS library',
    '/y become a vegetarian',
    '/t write a strongly worded letter',
    'Stop sleeping with the nightlight',
    'Never forget',
    '/r take out all the wasps tomorrow',
    'Take Suzy to the dog park',
    'Turn mental note into actual note',
    'Watch Dr. Strangelove',
    'Remind me to go to the movies on Sunday',
    '/r prank Taylor April 1st, ' + year,
    '/t read the new xkcd',
    'Do some jumping jacks',
    '/m say "yes" to everything for a month',
    'Learn the subtle art of beekeeping',
    'Clean my bike',
    '/r Check out the fall colors 10/03/' + year,
    'Learn how to tango',
    '/t shave',
    '/r Apple keynote Sept 9, ' + year,
    'Get on the good foot',
    'Do not seek the treasure',
    'Go to there',
    'Ludicrous speed, GO!',
    'The princess is in another castle',
    'Climb Mt. Doom',
    'Get off Reddit',
    'Step off his blue suede shoes',
    'Go outside, right now',
    'BOP IT',
    'Let\'s go bowling',
    'Open the pod bay doors',
    'Fix all the bugs',
    '/t Kill Bill'
  ]
}
